### ISSUE TITLE
Project Alternator

### ISSUE THREAD

**Issue by tzach** [alexdebrie/awesome-dynamodb#13]
Alternator is an AWS DynamoDB API **compatible**  project
https://github.com/scylladb/scylla/blob/master/docs/alternator/alternator.md

@alexdebrie if this is in the scope of awesome DynamoDB  I will be happy to send a PR

**Comment by alexdebrie** [comment]
Hey @tzach, sure thing! Would be a good add. Maybe in the Tools category?
