### ISSUE TITLE
Link to servicefull.cloud doesn't work anymore

### ISSUE THREAD

**Issue by NT-Timm** [alexdebrie/awesome-dynamodb#21]
The link of `[Lessons learned using Single-table design with DynamoDB and GraphQL in production](https://servicefull.cloud/blog/dynamodb-single-table-design-lessons/). A collection of great tips learned the hard way from [Rafal Wilinski](https://twitter.com/rafalwilinski). Rafal is the creator of Dynobase, listed in the [Tools](https://github.com/alexdebrie/awesome-dynamodb#tools) section below.`
To servicefull.cloud doesn't work anymore

**Comment by alexdebrie** [comment]
Thanks for the heads up, @NT-Timm ! Looks like it moved [here](https://www.rwilinski.me/blog/dynamodb-single-table-design-lessons/). Updated in the repo :)
